Repository team-xquare/xquare-android, pull requests merged in 2023-09, with the labels that each got.

#230 🔀 :: (#226) presigned url 기능 적용
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileViewModel.kt
  data/src/main/java/com/xquare/data/remote/FileUploadManager.kt
  data/src/main/java/com/xquare/data/remote/api/AttachmentApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/AttachmentRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/AttachmentRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/request/FileRequest.kt
  data/src/main/java/com/xquare/data/remote/request/attachment/FetchPreSignedUrlRequest.kt
  data/src/main/java/com/xquare/data/remote/response/attachment/FetchPreSignedUrlResponse.kt
  data/src/main/java/com/xquare/data/remote/response/attachment/FileResponse.kt
  data/src/main/java/com/xquare/data/repository/attachment/AttachmentRepositoryImpl.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
  domain/src/main/java/com/xquare/domain/entity/attachment/FileEntity.kt
  domain/src/main/java/com/xquare/domain/repository/attachment/AttachmentRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/attachment/UploadFileUseCase.kt
Labels: 기능 추가, 리팩토링

#233 🔀 :: (#232) Feature/227 fix bug report image invisible
  app/build.gradle
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugViewModel.kt
Labels: 버그

#235 🔀 :: (#234) Feature/228 server error
  data/src/main/java/com/xquare/data/Utils.kt
Labels: 버그

#237 🔀 :: (#236) Feature/229 save login state
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/XquareApplication.kt
Labels: 리팩토링

#239 🔀 :: (#238) Feature/230 light refactoring
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/AllMealScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/MealDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/point_history/PointHistoryItem.kt
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/release/ReleaseDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/schedule/ScheduleScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/signin/SignInScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/signin/SignInViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/splash/SplashScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/splash/SplashViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherViewModel.kt
  data/src/main/java/com/xquare/data/remote/response/notification/AlarmResponse.kt
  data/src/main/java/com/xquare/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/xquare/domain/entity/notification/AlarmEntity.kt
  domain/src/main/java/com/xquare/domain/repository/AuthRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/auth/FetchIdUseCase.kt
Labels: 리팩토링
