Repository team-xquare/xquare-android, pull requests merged in 2023-04, with the labels that each got.

#94 🔀 :: (#93) screen_visible
  app/src/main/java/com/xquare/xquare_android/feature/schedule/ScheduleScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/signup/SignUpScreen.kt
Labels: 기능 추가

#98 🔀 :: (#90) Home Pick Function
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassViewModel.kt
  app/src/main/java/com/xquare/xquare_android/navigation/AppNavigationItem.kt
  data/src/main/java/com/xquare/data/remote/api/PickApi.kt
  data/src/main/java/com/xquare/data/remote/api/TimetablesApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/PickRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/PickRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/datasource/TimetablesRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/TimetablesRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/response/pick/ClassPositionResponse.kt
  data/src/main/java/com/xquare/data/remote/response/pick/PassDataResponse.kt
  data/src/main/java/com/xquare/data/remote/response/pick/PassTimeResponse.kt
  data/src/main/java/com/xquare/data/remote/response/timetables/DayTimetablesResponse.kt
  data/src/main/java/com/xquare/data/repository/pick/PickRepositoryImpl.kt
  data/src/main/java/com/xquare/data/repository/timetables/TimetablesRepositoryImpl.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
  di/src/main/java/com/xquare/di/RemoteDataSourceModule.kt
  di/src/main/java/com/xquare/di/RepositoryModule.kt
  domain/src/main/java/com/xquare/domain/entity/pick/ClassPositionEntity.kt
  domain/src/main/java/com/xquare/domain/entity/pick/PassDataEntity.kt
  domain/src/main/java/com/xquare/domain/entity/pick/PassTimeEntity.kt
  domain/src/main/java/com/xquare/domain/entity/timetables/DayTimetableEntity.kt
  domain/src/main/java/com/xquare/domain/repository/pick/PickRepository.kt
  domain/src/main/java/com/xquare/domain/repository/timetables/TimetablesRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/pick/BackToClassRoomUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/pick/FetchClassPositionUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/pick/FetchPassDataUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/pick/FetchPassTimeUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/timetables/FetchPeriodUseCase.kt
Labels: 기능 추가

#109 🔀 :: (#108) fix auto login
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
Labels: 버그

#116 🔀 :: (#115) 대댓글 스크롤 오작동
  app/src/main/java/com/xquare/xquare_android/component/WebView.kt
Labels: 기능 추가

#114 (#113) Feature/113 fix_point_bug
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/deploymentTargetDropDown.xml
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/com/xquare/xquare_android/component/TextField.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/point_history/PointHistoryItem.kt
  app/src/main/java/com/xquare/xquare_android/feature/point_history/PointHistoryScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/point_history/PointHistoryViewModel.kt
  data/src/main/java/com/xquare/data/Utils.kt
  data/src/main/java/com/xquare/data/dao/HomeUserDao.kt
  data/src/main/java/com/xquare/data/dao/PointDao.kt
  data/src/main/java/com/xquare/data/local/XquareDatabase.kt
  data/src/main/java/com/xquare/data/local/datasource/HomeUserLocalDataSource.kt
  data/src/main/java/com/xquare/data/local/datasource/HomeUserLocalDataSourceImpl.kt
  data/src/main/java/com/xquare/data/local/datasource/PointLocalDataSource.kt
  data/src/main/java/com/xquare/data/local/datasource/PointLocalDataSourceImpl.kt
  data/src/main/java/com/xquare/data/local/entity/alarm/AlarmRoomEntity.kt
  data/src/main/java/com/xquare/data/local/entity/homeUser/HomeUserRoomEntity.kt
  data/src/main/java/com/xquare/data/local/entity/point/PointRoomEntity.kt
  data/src/main/java/com/xquare/data/remote/response/point/PointHistoriesResponse.kt
  data/src/main/java/com/xquare/data/repository/PointRepositoryImpl.kt
  data/src/main/java/com/xquare/data/repository/point/PointRepositoryImpl.kt
  data/src/main/java/com/xquare/data/repository/user/UserRepositoryImpl.kt
  di/src/main/java/com/xquare/di/LocalDataSourceModule.kt
  di/src/main/java/com/xquare/di/LocalModule.kt
  di/src/main/java/com/xquare/di/RepositoryModule.kt
  domain/src/main/java/com/xquare/domain/entity/point/PointHistoriesEntity.kt
  domain/src/main/java/com/xquare/domain/repository/PointRepository.kt
  domain/src/main/java/com/xquare/domain/repository/point/PointRepository.kt
  domain/src/main/java/com/xquare/domain/repository/user/UserRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/point/FetchBadPointHistoriesUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/point/FetchDormitoryPointUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/point/FetchGoodPointHistoriesUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/user/FetchUserSimpleDataUseCase.kt
Labels: 버그

#120 🔀 :: (#117) auto login no internet
  app/src/main/java/com/xquare/xquare_android/feature/splash/SplashViewModel.kt
  data/src/main/java/com/xquare/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/xquare/domain/repository/AuthRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/auth/AutoSignInUseCase.kt
Labels: 기능 추가

#130 ⚡️ :: (#129) Feature/129 bug api
  app/src/main/java/com/xquare/xquare_android/feature/all/AllScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugViewModel.kt
  data/src/main/java/com/xquare/data/remote/api/BugApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/BugRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/BugRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/request/bug/BugRequest.kt
  data/src/main/java/com/xquare/data/repository/bug/BugRepositoryImpl.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
  di/src/main/java/com/xquare/di/RemoteDataSourceModule.kt
  di/src/main/java/com/xquare/di/RepositoryModule.kt
  domain/src/main/java/com/xquare/domain/entity/bug/BugEntity.kt
  domain/src/main/java/com/xquare/domain/repository/bug/BugRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/bug/UploadBugUseCase.kt
Labels: 기능 추가

#131 ⚡️ :: (#122) Feature/130 today self study teacher
  app/build.gradle
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/feature/all/AllScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/AllMealScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherViewModel.kt
  app/src/main/java/com/xquare/xquare_android/navigation/AppNavigationItem.kt
  data/build.gradle
  data/src/main/java/com/xquare/data/Utils.kt
  data/src/main/java/com/xquare/data/remote/api/PickApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/PickRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/PickRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/response/pick/TodaySelfStudyTeacherResponse.kt
  data/src/main/java/com/xquare/data/repository/pick/PickRepositoryImpl.kt
  di/build.gradle
  domain/build.gradle
  domain/src/main/java/com/xquare/domain/entity/pick/TodaySelfStudyTeacherEntity.kt
  domain/src/main/java/com/xquare/domain/repository/pick/PickRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/pick/TodaySelfStudyTeacherUseCase.kt
Labels: 기능 추가, 프로젝트 설정

#133 ⚡️::(#132) 아이디 비번찾기 페이스북으로 이동
  app/src/main/java/com/xquare/xquare_android/feature/signin/SignInScreen.kt
Labels: 기능 추가

#135 ⚙️ :: minsdk version modify
  app/build.gradle
  data/build.gradle
  di/build.gradle
  domain/build.gradle
Labels: 프로젝트 설정

#139 🔀 :: (#138)Feature/133 Xquare design integration
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/component/ActionSheet.kt
  app/src/main/java/com/xquare/xquare_android/feature/all/AllScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/MealDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/onboard/OnboardScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/point_history/PointHistoryScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/schedule/ScheduleScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/schedule/WriteScheduleScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/today_teacher/TodayTeacherScreen.kt
Labels: 기능 추가, 리팩토링

#141 🔀 :: (#140) Feature/140 fix_room_version
  data/src/main/java/com/xquare/data/local/XquareDatabase.kt
Labels: 버그
