Repository team-xquare/xquare-android, pull requests merged in 2023-06, with the labels that each got.

#179 🔀 :: (#178) Feature/152 meal padding
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
Labels: chore

#185 🔀 :: (#184) Feature/154 change mypage
  app/src/main/java/com/xquare/xquare_android/feature/all/AllScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/all/AllViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileViewModel.kt
  data/src/main/java/com/xquare/data/remote/response/profile/ProfileResponse.kt
  domain/src/main/java/com/xquare/domain/entity/profile/ProfileEntity.kt
Labels: 기능 추가

#190 🔀 :: (#189) Feature/156 cancel call
  data/src/main/java/com/xquare/data/Utils.kt
Labels: 버그

#195 🔀 :: (#192) Feature/158_AllMealDetail_Modifiy_font
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/MealDetail.kt
Labels: chore, 리팩토링

#197 🔀 :: (#196) Feature/159 cut write schedule screen
  app/src/main/java/com/xquare/xquare_android/feature/schedule/WriteScheduleScreen.kt
Labels: chore

#200 🔀 :: (#186) Feature/155 improve navigation
  app/build.gradle
  app/src/main/java/com/xquare/xquare_android/component/BottomNavigation.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/schedule/ScheduleScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/schedule/TimetableViewModel.kt
  app/src/main/res/drawable/ic_thumbs_up.xml
  app/src/main/res/drawable/ic_thums_down.xml
  app/src/main/res/drawable/img_bad.png
  app/src/main/res/drawable/img_good.png
Labels: 기능 추가, 리팩토링
