Repository team-xquare/xquare-android, pull requests merged in 2023-05, with the labels that each got.

#149 🔀 ::(#148)Feature/137 Interceptor refactoring
  data/src/main/java/com/xquare/data/interceptor/AuthorizationInterceptor.kt
Labels: 리팩토링, 버그

#147 🔀 :: (#146)Feature/136 notification list
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/XquareApplication.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/MyFirebaseMessagingService.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/signin/SignInScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/splash/SplashViewModel.kt
  app/src/main/res/drawable/img_bad.png
  app/src/main/res/drawable/img_good.png
  app/src/main/res/values/strings.xml
  build.gradle
  data/build.gradle
  data/src/main/java/com/xquare/data/remote/api/NotificationApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/AlarmRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/request/auth/SignInRequest.kt
  data/src/main/java/com/xquare/data/remote/response/notification/AlarmResponse.kt
  data/src/main/java/com/xquare/data/repository/notification/AlarmRepositoryImpl.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
  domain/src/main/java/com/xquare/domain/entity/auth/SignInEntity.kt
  domain/src/main/java/com/xquare/domain/entity/notification/AlarmEntity.kt
  domain/src/main/java/com/xquare/domain/repository/notification/AlarmRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/notification/FetchAlarmUseCase.kt
Labels: 기능 추가

#151 🔀 ::(#150)Feature/138 bug_image
  app/build.gradle
  app/src/main/java/com/xquare/xquare_android/component/BottomNavigation.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugViewModel.kt
  data/src/main/java/com/xquare/data/remote/api/BugApi.kt
  data/src/main/java/com/xquare/data/remote/request/bug/BugRequest.kt
  domain/src/main/java/com/xquare/domain/entity/bug/BugEntity.kt
Labels: 기능 추가

#154 🔁 :: (#153) Feature/141 fix intercepter
  .gitignore
  app/google-services.json
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/XquareApplication.kt
  data/src/main/java/com/xquare/data/interceptor/AuthorizationInterceptor.kt
Labels: 기능 추가, 리팩토링, 버그

#162 🔀 :: (#156) Feature/143 fix screen cut off
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
Labels: 버그

#157 🔀 :: (#155) Feature/142 meal design
  app/src/main/java/com/xquare/xquare_android/feature/allmeal/MealDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
Labels: chore

#164 🔀 :: (#163) Feature/145 picnic design
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassViewModel.kt
  data/src/main/java/com/xquare/data/remote/response/pick/PassDataResponse.kt
  domain/src/main/java/com/xquare/domain/entity/pick/PassDataEntity.kt
Labels: 기능 추가, 리팩토링

#166 🔀 :: (165) Feature/146 fix pass bug
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/pick/PassViewModel.kt
  data/src/main/java/com/xquare/data/remote/response/pick/PassDataResponse.kt
  domain/src/main/java/com/xquare/domain/entity/pick/PassDataEntity.kt
Labels: 버그

#161 🔀 :: (#160) Feature/144 release note
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/feature/all/AllScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugViewModel.kt
  app/src/main/java/com/xquare/xquare_android/feature/release/ReleaseDetail.kt
  app/src/main/java/com/xquare/xquare_android/feature/release/ReleaseScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/release/ReleaseViewModel.kt
  app/src/main/java/com/xquare/xquare_android/navigation/AppNavigationItem.kt
  data/src/main/java/com/xquare/data/remote/api/BugApi.kt
  data/src/main/java/com/xquare/data/remote/api/ReportsApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/BugRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/BugRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/datasource/ReportRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/ReportRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/request/reports/BugRequest.kt
  data/src/main/java/com/xquare/data/remote/response/release/ReleaseResponse.kt
  data/src/main/java/com/xquare/data/repository/bug/BugRepositoryImpl.kt
  data/src/main/java/com/xquare/data/repository/reports/ReportRepositoryImpl.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
  di/src/main/java/com/xquare/di/RemoteDataSourceModule.kt
  di/src/main/java/com/xquare/di/RepositoryModule.kt
  domain/src/main/java/com/xquare/domain/entity/reports/BugEntity.kt
  domain/src/main/java/com/xquare/domain/entity/reports/ReleaseEntity.kt
  domain/src/main/java/com/xquare/domain/repository/bug/BugRepository.kt
  domain/src/main/java/com/xquare/domain/repository/reports/ReportRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/bug/UploadBugUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/release/FetchReleaseUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/release/UploadBugUseCase.kt
Labels: 기능 추가

#168 🔀 :: (#167)Meal Card Focusing
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
Labels: 기능 추가

#170 🔀 ::(#169) Feature/148 pass bug
  data/src/main/java/com/xquare/data/remote/response/pick/PassDataResponse.kt
  domain/src/main/java/com/xquare/domain/entity/pick/PassDataEntity.kt
Labels: 버그

#172 🔀 :: (#152) Feature/139 alarm setting
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/component/Switch.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/setting/SettingScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/setting/SettingViewModel.kt
  app/src/main/java/com/xquare/xquare_android/navigation/AppNavigationItem.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/xquare/data/remote/api/NotificationApi.kt
  data/src/main/java/com/xquare/data/remote/datasource/AlarmRemoteDataSource.kt
  data/src/main/java/com/xquare/data/remote/datasource/AlarmRemoteDataSourceImpl.kt
  data/src/main/java/com/xquare/data/remote/request/notification/ActivateAlarmRequest.kt
  data/src/main/java/com/xquare/data/remote/response/notification/AlarmCategoriesResponse.kt
  data/src/main/java/com/xquare/data/repository/notification/AlarmRepositoryImpl.kt
  domain/src/main/java/com/xquare/domain/entity/notification/ActivateAlarmEntity.kt
  domain/src/main/java/com/xquare/domain/entity/notification/AlarmCategoriesEntity.kt
  domain/src/main/java/com/xquare/domain/repository/notification/AlarmRepository.kt
  domain/src/main/java/com/xquare/domain/usecase/notification/ActivateAlarmUseCase.kt
  domain/src/main/java/com/xquare/domain/usecase/notification/FetchAlarmCategoriesUseCase.kt
Labels: 기능 추가

#175 🔀 :: (#174) Feature/150 branch error
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
  app/src/main/java/com/xquare/xquare_android/feature/home/HomeScreen.kt
Labels: 버그

#173 🔀 :: (#171) Feature/149 modify mypage
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileScreen.kt
  app/src/main/res/drawable/ic_camera.xml
Labels: 기능 추가, 프로젝트 설정

#177 🔀 :: (#176)Feature/151 tag bug
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/setting/SettingScreen.kt
Labels: 버그
