Repository team-xquare/xquare-android, pull requests merged in 2023-08, with the labels that each got.

#214 🔀 :: (#213) Feature/164 GitHub interworking
  app/src/main/java/com/xquare/xquare_android/feature/github/GithubScreen.kt
  app/src/main/java/com/xquare/xquare_android/theme/Color.kt
  app/src/main/res/drawable/ic_github_crown.xml
Labels: 기능 추가

#219 🔀 :: (#218) Feature/166 change url
  di/src/main/java/com/xquare/di/NetworkModule.kt
Labels: chore, 기능 추가

#217 🔀 :: (#216) Feature/165 login response change
  data/src/main/java/com/xquare/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/xquare/data/local/datasource/AuthLocalDataSourceImpl.kt
  data/src/main/java/com/xquare/data/local/preference/AuthPreference.kt
  data/src/main/java/com/xquare/data/local/preference/AuthPreferenceImpl.kt
  data/src/main/java/com/xquare/data/remote/response/auth/TokenResponse.kt
  data/src/main/java/com/xquare/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/xquare/domain/entity/auth/TokenEntity.kt
Labels: chore, 리팩토링

#222 🔀 :: (#221) Feature/167 WebView URL 수정
  app/src/main/java/com/xquare/xquare_android/MainActivity.kt
Labels: chore, 리팩토링

#224 🔀 :: (#223) Feature/168 webview auth bug
  app/src/main/java/com/xquare/xquare_android/component/WebView.kt
  app/src/main/java/com/xquare/xquare_android/feature/webview/CommonWebViewScreen.kt
  data/src/main/java/com/xquare/data/interceptor/AuthorizationInterceptor.kt
  data/src/main/java/com/xquare/data/remote/api/ProfileApi.kt
  di/src/main/java/com/xquare/di/NetworkModule.kt
Labels: 버그

#228 🔀 :: (#227) interceptor refresh token 저장 로직 추가
  data/src/main/java/com/xquare/data/interceptor/AuthorizationInterceptor.kt
Labels: 버그
