Repository team-xquare/xquare-android, pull requests merged in 2023-07, with the labels that each got.

#181 🔀 :: (#180) Feature/152 post bug image
  app/src/main/java/com/xquare/xquare_android/feature/bug/BugReportScreen.kt
  app/src/main/res/drawable/ic_add_photo.xml
Labels: 버그

#204 🔀 :: (#182) Feature/161 timetable focusing
  app/src/main/java/com/xquare/xquare_android/feature/schedule/ScheduleScreen.kt
Labels: 버그

#194 🔀 :: (#193) Feature/157 change setting page
  app/src/main/java/com/xquare/xquare_android/component/Switch.kt
  app/src/main/java/com/xquare/xquare_android/feature/alarm/AlarmScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/setting/SettingScreen.kt
  app/src/main/java/com/xquare/xquare_android/feature/setting/SettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 기능 추가

#198 🔀 :: (#191) Feature/160 modifiy mypage
  app/src/main/java/com/xquare/xquare_android/feature/profile/ProfileScreen.kt
  app/src/main/res/drawable/ic_add_gallery.xml
  data/src/main/java/com/xquare/data/remote/response/profile/ProfileResponse.kt
Labels: chore, 기능 추가

#206 🔀 :: (#205) Feature/162 webview success message
  app/src/main/java/com/xquare/xquare_android/feature/webview/CommonWebViewScreen.kt
  app/src/main/java/com/xquare/xquare_android/webview/WebToAppBridge.kt
  app/src/main/java/com/xquare/xquare_android/webview/data/WebViewSuccess.kt
Labels: 기능 추가
